### ISSUE TITLE
Build and host Docker containers

### ISSUE THREAD

**Issue by florianm** [getodk/central#165]
Short form: Would it make sense to let GitHub Actions (e.g. https://github.com/dbca-wa/central/actions) build the four custom Docker images (service, nginx, enketo, secrets) and push them to a GitHub container registry (e.g. https://github.com/orgs/dbca-wa/packages)?
Long form: https://forum.getodk.org/t/host-odk-central-docker-images-on-github-container-registry/29812
Baby steps: https://github.com/dbca-wa/central/blob/master/README_k8s.md (work in progress)

Questions:
What are good defaults for the volumes? @issa-tseng @matthew-white 
```
volumes:
  transfer: - use to prepare ZIP export including all media attachments of one form
  enketo_redis_main:
  enketo_redis_cache:
  secrets: are 100MB enough?
```
