### ISSUE TITLE
When running analyze in 50GB local database, Docker runs out of space due to shared memory

### ISSUE THREAD

**Issue by yanokwa** [getodk/central#600]
I tried to run `vacuum analyze` on a 50 GB database and got `pq: could not resize shared memory segment "/PostgreSQL.2058389254" to 12615680 bytes: No space left on device` error. 

This is because docker [by-default](https://github.com/moby/moby/issues/29492) restrict size of shared memory to 64MB.

https://meta.discourse.org/t/pg-throws-could-not-resize-shared-memory-segment-error/84744/8 suggests that 512MB is a safe default, and I can confirm that it fixed my problem. 

```
version: "3"
services:
  postgres14:
    build:
      context: .
      dockerfile: postgres14.dockerfile
    shm_size=512m
    volumes:
      - postgres14:/var/lib/odk/postgresql/14
```

I don't necessarily thing we should add this to the docker-compose, especially given that we'll be moving binaries out of the DB, but I figured I'd file an issue so the solution is out in the world.
